# Generated by Django 3.1.7 on 2021-02-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
